name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build-and-test:
    name: Build and Test
    strategy:
      matrix:
        go_version: ["1.21", "1.22"]
        os: [macos-latest, windows-latest, linux-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go_version }}

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
